import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "../ui/card";
import { Badge } from "../ui/badge";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Label } from "../ui/label";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "../ui/table";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "../ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../ui/select";
import { Plus, Calendar, Clock } from "lucide-react";
import { useAssignments, useCreateAssignment, useUpdateAssignmentStatus } from "../../hooks/useAssignments";
import { useVehicles } from "../../hooks/useVehicles";
import { useDrivers } from "../../hooks/useDrivers";
import { Assignment } from "../../types";
import { format } from "date-fns";

export function Assignments() {
  const { data: assignments, isLoading } = useAssignments();
  const { data: vehicles } = useVehicles();
  const { data: drivers } = useDrivers();
  const createAssignment = useCreateAssignment();
  const updateStatus = useUpdateAssignmentStatus();

  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [newAssignment, setNewAssignment] = useState<Partial<Assignment>>({
    status: "Scheduled",
  });

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newAssignment.vehicleId || !newAssignment.driverId || !newAssignment.startDate) return;

    try {
      await createAssignment.mutateAsync({
        vehicleId: newAssignment.vehicleId,
        driverId: newAssignment.driverId,
        status: "Scheduled",
        startDate: newAssignment.startDate,
        endDate: newAssignment.endDate || newAssignment.startDate,
        location: "TBD",
        progress: 0,
        id: "", // Will be generated by backend
      });
      setIsCreateOpen(false);
      setNewAssignment({ status: "Scheduled" });
    } catch (error) {
      console.error("Failed to create assignment", error);
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "Active":
        return "bg-green-500/10 text-green-500 hover:bg-green-500/20";
      case "Completed":
        return "bg-blue-500/10 text-blue-500 hover:bg-blue-500/20";
      case "Scheduled":
        return "bg-yellow-500/10 text-yellow-500 hover:bg-yellow-500/20";
      default:
        return "bg-gray-500/10 text-gray-500 hover:bg-gray-500/20";
    }
  };

  const getVehicleName = (id: string) => {
    const vehicle = vehicles?.find(v => v.id === id);
    return vehicle ? `${vehicle.make} ${vehicle.model}` : id;
  };

  const getDriverName = (id: string) => {
    const driver = drivers?.find(d => d.id === id);
    return driver ? driver.name : id;
  };

  if (isLoading) {
    return <div>Loading assignments...</div>;
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Assignments</h1>
          <p className="text-muted-foreground">
            Manage vehicle assignments and driver schedules
          </p>
        </div>
        <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="mr-2 h-4 w-4" />
              New Assignment
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Create New Assignment</DialogTitle>
            </DialogHeader>
            <form onSubmit={handleCreate} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="vehicle">Vehicle</Label>
                <Select
                  value={newAssignment.vehicleId}
                  onValueChange={(value) =>
                    setNewAssignment({ ...newAssignment, vehicleId: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select vehicle" />
                  </SelectTrigger>
                  <SelectContent>
                    {vehicles?.filter(v => v.status === 'Available').map((vehicle) => (
                      <SelectItem key={vehicle.id} value={vehicle.id}>
                        {vehicle.make} {vehicle.model}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="driver">Driver</Label>
                <Select
                  value={newAssignment.driverId}
                  onValueChange={(value) =>
                    setNewAssignment({ ...newAssignment, driverId: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select driver" />
                  </SelectTrigger>
                  <SelectContent>
                    {drivers?.filter(d => d.availability === 'Available').map((driver) => (
                      <SelectItem key={driver.id} value={driver.id}>
                        {driver.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="startDate">Start Date</Label>
                  <Input
                    id="startDate"
                    type="datetime-local"
                    value={newAssignment.startDate}
                    onChange={(e) =>
                      setNewAssignment({ ...newAssignment, startDate: e.target.value })
                    }
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="endDate">End Date</Label>
                  <Input
                    id="endDate"
                    type="datetime-local"
                    value={newAssignment.endDate}
                    onChange={(e) =>
                      setNewAssignment({ ...newAssignment, endDate: e.target.value })
                    }
                  />
                </div>
              </div>
              <div className="flex justify-end space-x-2">
                <Button
                  variant="outline"
                  type="button"
                  onClick={() => setIsCreateOpen(false)}
                >
                  Cancel
                </Button>
                <Button type="submit">Create Assignment</Button>
              </div>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">
              Active Assignments
            </CardTitle>
            <Clock className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {assignments?.filter((a) => a.status === "Active").length || 0}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">
              Scheduled Today
            </CardTitle>
            <Calendar className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {assignments?.filter((a) => {
                const today = new Date().toISOString().split('T')[0];
                return a.startDate.startsWith(today);
              }).length || 0}
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Recent Assignments</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Vehicle</TableHead>
                <TableHead>Driver</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Start Date</TableHead>
                <TableHead>End Date</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {assignments?.map((assignment) => (
                <TableRow key={assignment.id}>
                  <TableCell className="font-medium">
                    {getVehicleName(assignment.vehicleId)}
                  </TableCell>
                  <TableCell>{getDriverName(assignment.driverId)}</TableCell>
                  <TableCell>
                    <Badge
                      variant="secondary"
                      className={getStatusColor(assignment.status)}
                    >
                      {assignment.status}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    {format(new Date(assignment.startDate), "MMM d, yyyy HH:mm")}
                  </TableCell>
                  <TableCell>
                    {format(new Date(assignment.endDate), "MMM d, yyyy HH:mm")}
                  </TableCell>
                  <TableCell className="text-right">
                    {assignment.status === "Scheduled" && (
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() =>
                          updateStatus.mutate({ id: assignment.id, status: "Active" })
                        }
                      >
                        Start
                      </Button>
                    )}
                    {assignment.status === "Active" && (
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() =>
                          updateStatus.mutate({ id: assignment.id, status: "Completed" })
                        }
                      >
                        Complete
                      </Button>
                    )}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
